[SYSTEM]
reboot = reboot
halt = halt

[PIXELPILOT]
record = kill -SIGUSR2 $(pidof pixelpilot_mini_rk)

[GAMMA]
milos1 = gamma milos1
milos2 = gamma milos2
greg1 =  gamma greg1
reset = gamma reset

[VRX]
reboot = reboot

[RADIO]
; Trigger format: 1200<ch1<1500 = command
1200<ch1<1500 = echo "CH1 is in mid range"
1600<ch10<2000 = echo "ARM toggle high"
1600<ch5<2000 = echo "ARM toggle high"
